version: '3.8'
services:
  debuginfod:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./.env:/app/.env:ro
      - /usr/lib/debug:/usr/lib/debug:ro
    environment:
      - DEBUGINFOD_DB_PATH=/data/debuginfod.sqlite
      - DEBUGINFOD_SCAN_PATH=/usr/lib/debug
      - DEBUGINFOD_CACHE_DIR=/data/cache
